apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-eso-auth
  namespace: external-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-eso-auth-token
  namespace: external-secrets
  annotations:
    kubernetes.io/service-account.name: vault-eso-auth
type: kubernetes.io/service-account-token
